name: Test Redis Oplog
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        meteorRelease:
          - '--release 3.0.3'
    env:
      REDIS_OPLOG_SETTINGS: '{"debug":true}'
    steps:
      - uses: supercharge/redis-github-action@1.4.0
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 18
      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest
          npm ci

      - name: Run Tests
        run: |
          echo "Env: $NODE_ENV"
          export FORCE_COLOR=true
          export NODE_ENV=test

          mtest --package ./ --once ${{ matrix.meteorRelease }}
